{ ... }:
{
  imports = [
    ./fcitx5
    ./helix
    ./niri
    ./swaync
    ./vim
    ./wallpaper
    ./waybar
    ./zellij
    ./zsh
    ./alacritty.nix
    ./appflowy.nix
    ./bitwarden.nix
    ./chrome.nix
    ./claude-code.nix
    ./cursor.nix
    ./codex.nix
    ./flow-control.nix
    ./git.nix
    ./swaylock.nix
    ./swayidle.nix
    ./swaybg.nix
    ./vesktop.nix
    ./vscode.nix
    ./waybar.nix
    ./wofi.nix
    ./zed-editor.nix
    ./../../scripts/scripts.nix
  ];
}
