# https://github.com/helix-editor/helix/blob/master/languages.toml

# health check
# hx --health nix
[[language]]
name = "nix"
file-types = [ "nix" ]
indent = { tab-width = 2, unit = "  " }
language-servers = [ "nixd" ]
